### PR TITLE
Autoplay and Footer in News.js

### LINKED ISSUE #2: Make the video Autoplay
The embedded youtube video does not play automatically. It would be nice if the moment someone opens the page, it starts playing

### LINKED ISSUE #5: Add information about how to make your own fake link
In the pages with the video, add a banner at the bottom of the page that says something along the lines of "To create you own, head to <insert URL here>!"

### PR DESCRIPTION
**Pull request by ShreyaPanale**
Fixes 2 and 5 

Edit:
Fixes #5

### CODE REVIEW

**Review by srujandeshpande — CHANGES_REQUESTED** [review]
`./src/News.js
Module not found: Can't resolve 'react-player' in '/home/srujandeshpande/Projects/breaking-news/src'`

I'm getting this error on running

**Comment by ShreyaPanale** [comment]
@srujandeshpande can you check now?

**Review by srujandeshpande — CHANGES_REQUESTED** [review]
Autoplay is not working

**Review by srujandeshpande — APPROVED** [review]
The footer is approved

**Comment by srujandeshpande** [comment]
!bounty 20

**Comment by srujandeshpande** [comment]
Merged for the footer. Autoplay not working

**Pull request merged**
